/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-11-24 01:23:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>대철이제철 게시판 프로젝트</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .welcome-container {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 60px 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome-title {\r\n");
      out.write("            font-size: 36px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #03C75A;\r\n");
      out.write("            margin-bottom: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome-subtitle {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            color: #666666;\r\n");
      out.write("            margin-bottom: 48px;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("            gap: 24px;\r\n");
      out.write("            margin: 48px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card {\r\n");
      out.write("            padding: 32px 24px;\r\n");
      out.write("            background-color: #F7F9FA;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card:hover {\r\n");
      out.write("            transform: translateY(-4px);\r\n");
      out.write("            box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);\r\n");
      out.write("        }\r\n");
      out.write("        .feature-icon {\r\n");
      out.write("            font-size: 48px;\r\n");
      out.write("            margin-bottom: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-title {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #222222;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-desc {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #666666;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"welcome-container\">\r\n");
      out.write("            <h1 class=\"welcome-title\">대철이제철 게시판 프로젝트</h1>\r\n");
      out.write("            <p class=\"welcome-subtitle\">환영합니다! 네이버 스타일의 모던한 게시판입니다.</p>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"feature-grid\">\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <div class=\"feature-icon\">✍️</div>\r\n");
      out.write("                    <div class=\"feature-title\">자유로운 글쓰기</div>\r\n");
      out.write("                    <div class=\"feature-desc\">누구나 쉽게 게시글을 작성하고 공유할 수 있습니다.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <div class=\"feature-icon\">👥</div>\r\n");
      out.write("                    <div class=\"feature-title\">회원 관리</div>\r\n");
      out.write("                    <div class=\"feature-desc\">안전한 회원가입과 로그인 시스템을 제공합니다.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <div class=\"feature-icon\">🔒</div>\r\n");
      out.write("                    <div class=\"feature-title\">관리자 기능</div>\r\n");
      out.write("                    <div class=\"feature-desc\">체계적인 게시판 및 회원 관리가 가능합니다.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"menu\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/MemberServlet?command=login_form\" style=\"background-color: #03C75A; color: white; border: none;\">로그인</a>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/MemberServlet?command=join_form\">회원가입</a>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/BoardServlet?command=board_list\">게시판</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
